### PR TITLE
Add download function

### PR DESCRIPTION
**Pull request by brambozz**
This PR adds a download function, such that in a notebook we can do:

```python
from ismi import download_data

download_data("assignment_1.zip", "https://link.to/assignment_1.zip")
```

Could you check if I did things properly with the test?

Also, I put the function in `__init__.py` now, not sure if that is the best place.

### CODE REVIEW

**Comment by joeranbosma** [comment]
I think it would be better to make a dedicated file for the download function, rather than putting it in the init file. The function can then be imported in the init file and exposed ([like here](https://github.com/DIAGNijmegen/picai_prep/blob/main/src/picai_prep/__init__.py)).

**Comment by brambozz** [comment]
Thanks, that's what I was looking for. I moved it to ismi.io.

I have one final thing that is not working, the test. I followed the dev readme, but when I run `pytest`, I get:

```
======================================================================== test session starts =========================================================================
platform linux -- Python 3.8.15, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/bram/repos/ismi, configfile: pyproject.toml, testpaths: tests
plugins: cov-2.12.1, anyio-3.6.2
collected 0 items                                                                                                                                                    


---------- coverage: platform linux, python 3.8.15-final-0 -----------
Name                   Stmts   Miss  Cover
------------------------------------------
src/ismi/__init__.py       2      0   100%
src/ismi/io.py            23      3    87%
------------------------------------------
TOTAL                     25      3    88%

======================================================================= no tests ran in 4.60s ========================================================================
```

It seems it scans `tests`, but somehow does not find `test_download_data.py`. If I run it manually with `python tests/test_download_data.py` it runs fine. Any ideas?

**Comment by joeranbosma** [comment]
Great!

The pytest module works slightly different: the test code should be confined in a function called `test_[xyz]` for it to be picked up. I pushed my proposed changed which fixes the pytest issue.

If you want to run the test directly, you could add the following to run the test with `python ...`:

```python
if __name__ == "__main__":
    test_download_data()
```

**Review by joeranbosma — APPROVED** [review]

**Comment by brambozz** [comment]
Ah, the function has to be that format as well, good to know! Type hints looking great :sunglasses:

**Pull request merged**
